/**
 * Every user-facing string of the web app, in Henosis's voice (docs/15_copy.md): calm, specific,
 * no AI-speak. Views import `copy` and never carry a literal of their own. Strings that take
 * data are functions, so word order and plurals live here too.
 *
 * Grouped by surface: shell (sidebar, account), home, session (top row, stream, steps,
 * approvals, composer, details drawer), project, team, notify (browser notifications) and the
 * five status words.
 */

/** "1 approval" / "3 approvals". */
export const plural = (n: number, one: string, many = `${one}s`): string =>
  `${n} ${n === 1 ? one : many}`;

/** "1,800 tokens", with the thousands separated the same way everywhere. */
export const tokens = (n: number): string => `${n.toLocaleString("en-US")} tokens`;

/** A rating average with at most one decimal: 4, 4.5, 4.3. */
export const average = (n: number): string => String(Math.round(n * 10) / 10);

/** The five status words, the same everywhere (sidebar dot, top row, fleet rows, Slack). */
export const status = {
  running: "Running",
  awaiting_approval: "Awaiting approval",
  blocked: "Blocked",
  paused: "Paused",
  idle: "Idle",
  cancelled: "Cancelled",
  closed: "Closed",
  offline: "Offline",
} as const;

export const copy = {
  product: "Henosis",
  loading: "Loading…",
  roles: { driving: "driving", you: "you" },

  shell: {
    menu: "Menu",
    closeMenu: "Close menu",
    sidebar: "Sidebar",
    newSession: "New session",
    searchSessions: "Search sessions",
    projects: "Projects",
    agents: "Agents",
    memory: "Memory",
    orgMemory: (org: string) => `${org} memory`,
    defaultTeam: "Default team",
    chats: "Chats",
    orgChats: (org: string) => `${org} chats`,
    newGroup: "New group",
    recents: "Recents",
    signIn: "Sign in",
  },

  account: {
    menu: "Account",
    theme: "Theme",
    themeAuto: "Auto",
    themeLight: "Light",
    themeDark: "Dark",
    notifications: "Notifications",
    notifyOn: "On while this tab is hidden",
    notifyOnDesktop: "On while Henosis is in the background",
    notifyBlocked: "Blocked by the browser",
    notifyUnsupported: "Not available here",
    notifyTurnOn: "Turn on",
    changeIdentity: "Change identity",
    signOut: "Sign out",
  },

  home: {
    title: "Home",
    heroTitle: "Many hands, one team. One holds the baton at a time.",
    heroLine: "Watch the course, redirect, hand off.",
    needsIdentity: "Pick an identity to open that page.",
    signedInAs: (name: string) => `Signed in as ${name}`,
    unknownToServer: " · unknown to the server; first in owns a session",
    change: "Change",
    yourName: "Your name",
    userId: "User id",
    userIdHint: "as in users.json",
    token: "Token (optional)",
    tokenHint: "only if the server requires one",
    continue: "Continue",
    cancel: "Cancel",
    projects: "Projects",
    meFailed: (error: string) => `Could not load /api/me: ${error}`,
    noProjects: "No projects for you yet. Ask a lead to add you.",
    open: "Open",
    teamOverview: "team overview",
    project: "Project",
    sessionId: "Session id",
    sessionIdHint: "Open a session by id",
    openSession: "Open session",
    planFirst: "Plan first",
    planFirstHint: "The agent proposes a plan; the team rates it before any work",
    tokenBudget: "Token budget",
    tokenBudgetHint: "tokens, optional",
  },

  session: {
    joining: "Joining…",
    connecting: "Connecting…",
    reconnecting: "Reconnecting…",
    present: (names: string[]) => `Present: ${names.join(", ")}`,
    avatarTitle: (name: string, role: string, driving: boolean) =>
      `${name} · ${role}${driving ? " · driving" : ""}`,
    more: (n: number) => `+${n}`,
    presentSummary: (summary: string) => `Present: ${summary}`,
    writing: " · writing",
    share: "Share",
    copied: "Copied",
    details: "Details",
    copyLink: "Copy this link",
    linkCopied: "Link copied",
    copyFailed: "Could not copy the link",
  },

  stream: {
    label: "Conversation",
    empty: "Set a goal to start the agent.",
    note: "note",
    interrupt: "interrupt",
    turnEnded: (turn: number, reason: string, summary: string | undefined) =>
      `Turn ${turn} ${reason}${summary ? ` · ${summary}` : ""}`,
    projectDirection: (who: string, text: string) => `${who} set a project direction: ${text}`,
    picked: (who: string) => `${who} picked a direction`,
    withdrew: (who: string) => `${who} withdrew a directive`,
    offered: (who: string, to: string) => `${who} offers the baton to ${to}`,
    hasTheBaton: (who: string) => `${who} has the baton`,
    declined: (who: string) => `${who} declined the baton`,
    joined: (who: string, role: string) => `${who} joined as ${role}`,
    left: (who: string) => `${who} left`,
    roleChanged: (who: string, role: string) => `${who} is now ${role}`,
    checkpoint: (label: string) => `Checkpoint ${label}`,
    forked: (branch: string, from: string) => `Branch ${branch} forked from ${from}`,
    folded: (source: string, base: string, conflicts: number) =>
      `United ${source} into ${base}${conflicts ? ` · ${plural(conflicts, "conflict")}` : ""}`,
    writeRefused: (path: string, holder: string) => `Write to ${path} refused: held by ${holder}`,
    fleetContention: (kind: string, resource: string, others: string[], resolved: boolean) =>
      `${resolved ? "Resolved: " : "Fleet contention: "}${kind} on ${resource} with ${others.join(", ") || "another session"}`,
    /** "Two directions for <b>scope</b>. The agent holds this scope until you pick one." */
    contentionBefore: "Two directions for ",
    contentionAfter: ". The agent holds this scope until ",
    youPick: "you pick one",
    theyPick: (who: string) => `${who} picks one`,
    pick: "Pick",
    withdraw: "Withdraw",
    offeredYou: (who: string) => `${who} offers you the fold.`,
    accept: "Accept",
    decline: "Decline",
    planDecided: (who: string, status: "approved" | "revise" | "rejected") =>
      status === "approved"
        ? `${who} approved the plan`
        : status === "revise"
          ? `${who} asked for a revised plan`
          : `${who} rejected the plan`,
  },

  /** Plan first: the card in the stream, its ratings and the words around it. */
  plan: {
    title: "Plan",
    heading: (n: number) => `Plan · ${plural(n, "step")}`,
    proposedOn: (turn: number) => `proposed on turn ${turn}`,
    status: {
      proposed: "Waiting for ratings",
      approved: "Approved",
      revise: "Revision asked",
      rejected: "Rejected",
      done: "Done",
    },
    /** The same states as one lowercase word for the progress line. */
    statusWord: {
      proposed: "waiting",
      approved: "approved",
      revise: "revision asked",
      rejected: "rejected",
      done: "done",
    },
    stepStatus: { pending: "pending", running: "running", done: "done" },
    est: (n: number) => `~${n.toLocaleString("en-US")}`,
    used: (n: number) => `${n.toLocaleString("en-US")} used`,
    totals: (est: number, used: number, budget: number | null) =>
      `${tokens(est)} estimated${used ? ` · ${tokens(used)} used` : ""}${
        budget ? ` · budget ${tokens(budget)}` : ""
      }`,
    yourRating: "Your rating",
    rate: (n: number) => `Rate ${n} of 5`,
    noteHint: "A note with your rating (optional)",
    progress: (count: number, min: number, avg: number, status: string) =>
      `${count} of ${min} ratings${count ? ` · ${average(avg)} average` : ""} · ${status}`,
    needs: (min: number, bar: number) => `needs ${min} at ${average(bar)}+`,
    rated: (who: string, rating: number) => `${who} rated it ${rating}`,
    approveNow: "Approve now",
    askRevise: "Ask to revise",
    reject: "Reject",
    decisionHint: "A note with your decision (optional)",
    decidedBy: (who: string) => `by ${who}`,
    byPolicy: "by the team's ratings",
    replaced: "Replaced by a newer plan.",
    planning: "Planning",
    waits: "The plan waits for ratings",
    waitingFor: "ratings on the plan",
  },

  /** What a tool call does, in words: `ask` for the approval sentence, `doing`/`done` for the step. */
  steps: {
    read: (p: string) => ({ ask: `read ${p}`, doing: `Reading ${p}`, done: `Read ${p}` }),
    write: (p: string) => ({ ask: `write ${p}`, doing: `Writing ${p}`, done: `Wrote ${p}` }),
    delete: (p: string) => ({ ask: `delete ${p}`, doing: `Deleting ${p}`, done: `Deleted ${p}` }),
    list: { ask: "list the workspace", doing: "Listing files", done: "Listed files" },
    shell: (cmd: string) => ({
      ask: `run \`${cmd}\``,
      doing: `Running shell: ${cmd}`,
      done: `Ran shell: ${cmd}`,
    }),
    deploy: (env: string) => ({
      ask: `deploy to ${env}`,
      doing: `Deploying to ${env}`,
      done: `Deployed to ${env}`,
    }),
    remember: (key: string) => ({
      ask: `remember ${key}`,
      doing: `Remembering ${key}`,
      done: `Remembered ${key}`,
    }),
    recall: { ask: "recall team memory", doing: "Recalling memory", done: "Recalled memory" },
    claim: { ask: "claim a resource", doing: "Claiming", done: "Claimed" },
    release: { ask: "release a claim", doing: "Releasing", done: "Released" },
    other: (name: string, args: string) => ({ ask: `${name} ${args}`, doing: name, done: name }),
    exitOk: " · exit 0",
    failed: " · failed",
  },

  approval: {
    approved: "Approved",
    denied: "Denied",
    wants: (ask: string, risk: string, rule: string) =>
      `The agent wants to ${ask} (${risk}); needs ${rule}.`,
    vote: (who: string, approve: boolean, rating: number | null = null) =>
      `${who} ${approve ? "approved" : "denied"}${rating ? ` · ${rating} of 5` : ""}`,
    approve: "Approve",
    deny: "Deny",
    /** A release gate: how many rated approvals there are against the rule's minimum. */
    progress: (count: number, min: number, avg: number) =>
      `${count} of ${min} raters${count ? ` · ${average(avg)} average` : ""}`,
    rateHint: "Rate it before you approve; 4 if you leave it",
    noteHint: "A note with your vote (optional)",
    approveRated: (action: string, risk: string) => `Approve ${action} (${risk}) with a rating`,
    ratePrompt: "Rate it 1 to 5 (Enter for 4)",
  },

  composer: {
    label: "Steer the agent",
    labelTeam: "Say to the team",
    sendTo: "Send to",
    toAgent: "Agent",
    toTeam: "Team",
    placeholderTeam: "Say something to the people in this session",
    directive: "Directive",
    placeholder: "Steer the agent",
    placeholderFor: (mode: string) => `Send "${mode}"`,
    modeAndScope: "Mode and scope",
    send: "Send",
    mode: "Mode",
    scope: "Scope",
    scopeDefault: "goal",
    interruptNow: "Interrupt now",
    viewingPast: "Viewing the past · ",
    returnToNow: "Return to now",
    reconnecting: "Reconnecting · ",
    planWaits: "The plan waits for ratings",
    hint: (name: string, role: string, driving: boolean) =>
      `Enter to send · Shift+Enter for a new line · ? for shortcuts · as ${name}, ${role}${driving ? ", driving" : ""}`,
  },

  details: {
    title: "Details",
    close: "Close details",
    intent: "Intent",
    noGoal: "No goal yet.",
    always: "always",
    fromProject: " · project",
    held: (scopes: string[]) => `Held until a pick: ${scopes.join(", ")}`,
    control: (control: string, interrupt: boolean, turn: number) =>
      `${control}${interrupt ? " · interrupt pending" : ""} · turn ${turn}`,
    pause: "Pause",
    resume: "Resume",
    people: "People",
    you: " (you)",
    away: " · away",
    handOff: "Hand off",
    roleOf: (name: string) => `Role of ${name}`,
    alone: "Nobody else here yet. Share the link.",
    branches: "Branches",
    here: " · here",
    switch: "Switch",
    foldInto: (branch: string) => `Unite into ${branch}`,
    branchName: "New branch name",
    branchHint: "try/idea",
    fork: "Fork",
    files: (n: number) => plural(n, "file"),
    conflicts: (n: number) => ` · ${plural(n, "conflict")}`,
    checkpoints: (n: number) => ` · ${n} checkpoints`,
    checkpoint: "Checkpoint",
    conflict: " · conflict",
    memory: "Memory",
    refresh: "Refresh",
    catchUp: "Catch-up",
    briefHint: "A brief of what happened since you were last here.",
    askBrief: "Ask for brief",
    memoryEmpty: "Nothing remembered for this project yet.",
    memoryEmptyHint: "Nothing remembered here yet; ask the agent to remember something.",
    writeToAgent: "Write to the agent",
    memoryConflict: "Conflict · ",
    usage: "Usage",
  },

  /** Token usage: the chip in the top row, the Usage section of the drawer, card feet. */
  usage: {
    /** "12.4k tokens"; `n` is already the short form. */
    chip: (n: string) => `${n} tokens`,
    input: "Input",
    output: "Output",
    cacheRead: "Cache read",
    cacheWrite: "Cache write",
    budget: "Budget",
    noBudget: "No budget set",
    /** "12,400 of 50,000 · 25%" */
    ofBudget: (used: string, budget: string, pct: number) => `${used} of ${budget} · ${pct}%`,
    left: (n: string) => `about ${n} left`,
    nearing: "Nearing the budget",
    over: "Over the budget",
    byTurn: "By turn",
    turn: (n: number) => `Turn ${n}`,
    noTurns: "No turns yet.",
    /** The chip's accessible name: "Tokens: 12,400 used, 25% of the budget". */
    label: (used: string, pct: number | null) =>
      `Tokens: ${used} used${pct === null ? "" : `, ${pct}% of the budget`}`,
  },

  project: {
    sessions: "Sessions",
    agents: "Agents",
    withOthers: (names: string[]) => ` with ${names.join(", ")}`,
    noSessions: "No sessions yet.",
    emptySessions: "No sessions in this project yet.",
    startOne: "Start one",
    memoryEmptyHint: "Nothing remembered here yet; an agent adds facts as it works.",
    startSession: "Start a session",
    approvalsWaiting: (n: number) => ` · ${plural(n, "approval")} waiting`,
    newSession: "New session",
    title: "Title",
    titleHint: "What is this session for?",
    sessionId: "Session id",
    open: "Open",
    planFirst: "Plan first",
    tokenBudget: "Token budget",
    tokenBudgetHint: "tokens, optional",
    contentions: "Contentions",
    bothWant: "Both want",
    mergeConflictOn: "Merge conflict on",
    overlapOn: "Overlapping work on",
    and: " and ",
    wins: (who: string) => `${who} wins`,
    dismiss: "Dismiss",
    dismissed: "dismissed",
    direction: "Project direction",
    directionHint: "Set direction for everyone in this project",
    constrainHint: "A standing constraint for every session",
    steerHint: "A steer every session follows",
    setDirection: "Set direction",
    withdraw: (text: string) => `Withdraw: ${text}`,
    teamMemory: "Team memory",
    allMemory: "All memory",
    disagree: "Two entries disagree on ",
    memoryEmpty: "Nothing remembered for this project yet.",
    brief: "Brief",
    tokens: (n: string) => ` · ${n} tokens`,
  },

  viz: {
    tokens: "tokens",
    nothingYet: "Nothing to show yet.",
    table: "Table",
    chart: "Chart",
    name: "Name",
    share: "Share",
    when: "When",
  },
  team: {
    refresh: "Refresh",
    overview: "Overview",
    tokensTotal: "Tokens",
    tokensDetail: (input: string, output: string) => `${input} in · ${output} out`,
    agentsOpen: "Agents",
    agentsDetail: (team: number, solo: number) => `${team} in teams · ${solo} solo`,
    needsYouTile: "Needs you",
    needsDetail: (approvals: number, contentions: number) =>
      `${plural(approvals, "approval")} · ${plural(contentions, "contention")}`,
    membersTile: "Members",
    membersDetail: (people: number, agents: number) =>
      `${plural(people, "person", "people")} · ${plural(agents, "agent")}`,
    tokensByProject: "Tokens by project",
    tokensByPerson: "Tokens by person",
    tokensByAgent: "Tokens by agent",
    tokensOverTurns: "Tokens over turns",
    turnBucket: (from: number, to: number) =>
      from === to ? `turn ${from}` : `turns ${from}–${to}`,
    calls: (n: number) => plural(n, "call"),
    membersAndAgents: "Members and agents",
    crews: "Crews",
    crewLine: (n: number, owners: string) => `${plural(n, "agent")} · ${owners}`,
    agentOf: (owner: string) => `${owner}'s agent`,
    inProject: (p: string) => `in ${p}`,
    noProjects: "No projects in this team are visible to you.",
    summary: (open: number, projects: number, counts: string, needs: number) =>
      `${plural(open, "open session")} across ${plural(projects, "project")}${counts ? `: ${counts}` : ""}. ${
        needs === 0
          ? "Nothing needs you right now."
          : `${plural(needs, "thing")} need${needs === 1 ? "s" : ""} you.`
      }`,
    counts: {
      running: (n: number) => `${n} running`,
      awaiting_approval: (n: number) => `${n} awaiting approval`,
      blocked: (n: number) => `${n} blocked`,
      paused: (n: number) => `${n} paused`,
      idle: (n: number) => `${n} idle`,
    },
    needsYou: "Needs you",
    nothingWaiting: "Nothing waiting.",
    approvalsIn: (n: number, title: string) => `${plural(n, "approval")} waiting in ${title}`,
    open: "Open",
    resolve: "Resolve",
    on: " on ",
    projects: "Projects",
    noOpenSessions: "no open sessions",
    recentHandoffs: "Recent handoffs",
    noHandoffs: "None offered to you yet.",
    noHandoffsYet: "No one has offered you a session yet.",
    turnOnNotifications: "Turn on notifications",
    openProject: "Open a project",
    noProjectsYet: "No projects in this team are visible to you yet.",
    tryDemo: "Try the demo session",
    new: "New",
    housekeeping: "Memory housekeeping",
    browseMemory: "Browse memory",
    curatorHint: (org: string) =>
      `One curator pass over ${org}: compact grown scopes, flag stale entries, list conflicts.`,
    run: "Run",
    running: "Running…",
    runAgain: "Run again",
    nothingToTidy: "Nothing to tidy.",
    foldedIn: (n: number) => `Compacted ${n} entries in `,
    level: (n: number) => `level ${n}`,
    stale: "Stale: ",
    staleLine: (author: string, unreadFor: number) =>
      `by ${author} · unread for ${unreadFor} events`,
    conflictOn: "Conflict on ",
  },

  /** Groups and chats (views/ChatView.tsx): people and agents in one circle. */
  chat: {
    title: "Chats",
    messages: "Messages",
    groups: "Groups",
    noGroups: "No groups yet. Start one with a person and an agent.",
    notAMember: "You are not in this group. Ask its creator or a lead to add you.",
    unknownGroup: "No such group here.",
    joining: "Opening…",
    members: "Members",
    memberCount: (n: number) => plural(n, "member"),
    closeMembers: "Close members",
    people: "People",
    agents: "Agents",
    you: " (you)",
    creator: "created it",
    inSession: "Open session",
    remove: "Remove",
    leave: "Leave",
    addPerson: "Add a person",
    addAgent: "Add an agent",
    add: "Add",
    nobodyToAdd: "Everyone in the organisation is already here.",
    noAgentsToAdd: "No live agents to add; start a session first.",
    agentOf: (owner: string, project: string) => `${owner}'s agent · ${project}`,
    composer: "Write a message",
    label: "Message",
    placeholder: (group: string) => `Say something in #${group}`,
    placeholderMention: "Say something; @ mentions a person or an agent",
    send: "Send",
    hint: "Enter to send · Shift+Enter for a new line · @ to mention a person or an agent",
    mentionList: "Mention",
    agentReplied: "replied",
    inReplyTo: "in reply to",
    turn: (n: number) => `turn ${n}`,
    empty: "Nothing said yet. Mention an agent with @ to bring it in.",
    today: "Today",
    yesterday: "Yesterday",
    newGroup: "New group",
    name: "Name",
    nameHint: "Invoice rollout",
    purpose: "Purpose",
    purposeHint: "What is this group for?",
    scope: "Scope",
    scopeOrg: "Whole organisation",
    scopeTeam: (team: string) => `Team ${team}`,
    scopeProject: (project: string) => `Project ${project}`,
    membersHint: "Pick people and agents. You are in it already.",
    create: "Create group",
    cancel: "Cancel",
    created: (name: string) => `#${name} created`,
    renamed: "Renamed",
    noOrg: "Pick an organisation first.",
    live: (status: string) => status,
  },

  notify: {
    mentionTitle: (who: string, group: string) => `${who} mentioned you in #${group}`,
    approvalTitle: "Approval needed",
    approvalBody: (call: string, risk: string, where: string) => `${call} [${risk}] in ${where}`,
    handoffTitle: "You are offered the baton",
    handoffBody: (who: string, where: string) => `${who} wants to hand off ${where}`,
    contentionTitle: "Fleet contention",
    contentionBody: (kind: string, resource: string) => `${kind} on ${resource}`,
    planTitle: "A plan waits for your rating",
    planBody: (steps: number, where: string) => `${plural(steps, "step")} in ${where}`,
  },
} as const;
