//! The daily desk report (Markdown plus CSV side files).

use std::collections::{BTreeMap, BTreeSet};

use basis_core::types::*;
use rust_decimal::prelude::ToPrimitive;
use time::Date;

use crate::metrics::Metrics;

pub struct ReportInputs<'a> {
    pub date: Date,
    pub estimates: &'a [IndexEstimate],
    pub settlements: &'a [SettlementEstimate],
    pub curve: &'a [ForwardCurvePoint],
    pub spreads: &'a [Spread],
    pub positions: &'a [Position],
    pub equity: &'a [DailyEquity],
    pub signals: &'a [Signal],
    pub standardized: &'a [StandardizedObservation],
    pub observations: &'a [PriceObservation],
    pub metrics: Option<&'a Metrics>,
    pub synthetic_markets: bool,
    pub risk_limits: Option<(f64, f64)>, // (max gross notional, max net gpu hours)
}

pub struct Report {
    pub markdown: String,
    pub summary: Vec<(String, String)>,
    pub data_quality: Vec<Vec<String>>,
}

fn md_table(out: &mut String, headers: &[&str], rows: &[Vec<String>]) {
    if rows.is_empty() {
        out.push_str("_no rows_\n\n");
        return;
    }
    out.push_str("| ");
    out.push_str(&headers.join(" | "));
    out.push_str(" |\n|");
    for _ in headers {
        out.push_str("---|");
    }
    out.push('\n');
    for r in rows {
        out.push_str("| ");
        out.push_str(&r.join(" | "));
        out.push_str(" |\n");
    }
    out.push('\n');
}

fn f(x: f64, dp: usize) -> String {
    if x.is_finite() {
        format!("{x:.dp$}")
    } else {
        "-".into()
    }
}

pub fn build(inp: &ReportInputs) -> Report {
    let d = inp.date;
    let ds = basis_core::date_serde::fmt(d);
    let mut md = String::new();
    let mut summary: Vec<(String, String)> = Vec::new();
    md.push_str(&format!("# Basis desk report: {ds}\n\n"));
    if inp.synthetic_markets {
        md.push_str("> **Synthetic markets.** Futures and index prints in this store are generated by `basis synth`, including scripted mispricing episodes. Every P&L figure below validates plumbing, not alpha.\n\n");
    }
    md.push_str("> Hypothetical performance. Paper trading only; no orders are sent to any venue. Contract specifications in `config/contracts.toml` are placeholders pending verification against exchange rulebooks.\n\n");

    // 1. Nowcasts
    md.push_str("## 1. Index nowcasts\n\n");
    let mut latest: BTreeMap<String, &IndexEstimate> = BTreeMap::new();
    let mut prev: BTreeMap<String, &IndexEstimate> = BTreeMap::new();
    for e in inp.estimates.iter().filter(|e| e.date <= d) {
        let k = e.index_id.to_string();
        match latest.get(&k) {
            Some(cur) if cur.date >= e.date => {}
            _ => {
                if let Some(cur) = latest.insert(k.clone(), e) {
                    prev.insert(k, cur);
                }
            }
        }
    }
    let rows: Vec<Vec<String>> = latest
        .values()
        .map(|e| {
            let chg = prev
                .get(&e.index_id.to_string())
                .map(|p| f(e.estimate - p.estimate, 4))
                .unwrap_or("-".into());
            summary.push((format!("nowcast.{}", e.index_id), f(e.estimate, 4)));
            vec![
                e.index_id.to_string(),
                basis_core::date_serde::fmt(e.date),
                f(e.estimate, 4),
                format!("[{}, {}]", f(e.ci_low, 3), f(e.ci_high, 3)),
                format!("{}/{}", e.n_used, e.n_obs),
                e.n_providers.to_string(),
                chg,
            ]
        })
        .collect();
    md_table(
        &mut md,
        &[
            "index",
            "date",
            "estimate $/GPU-h",
            "90% CI",
            "used/obs",
            "providers",
            "chg vs prev",
        ],
        &rows,
    );

    // 2. Settlement estimates
    md.push_str("## 2. Settlement estimates for listed contracts\n\n");
    let rows: Vec<Vec<String>> = inp
        .settlements
        .iter()
        .filter(|s| s.as_of == d)
        .map(|s| {
            vec![
                s.contract_id.to_string(),
                s.style.to_string(),
                format!("{}/{}", s.realized_days, s.realized_days + s.remaining_days),
                f(s.estimate, 4),
                f(s.se, 4),
            ]
        })
        .collect();
    md_table(
        &mut md,
        &["contract", "style", "realized/total days", "estimate", "se"],
        &rows,
    );

    // 3. Curve vs fair value
    md.push_str("## 3. Forward curve vs fair value\n\n");
    let curve_date = inp
        .curve
        .iter()
        .filter(|c| c.as_of <= d)
        .map(|c| c.as_of)
        .max();
    let basis_by_contract: BTreeMap<&str, &Spread> = inp
        .spreads
        .iter()
        .filter(|s| s.date == d && s.kind == SpreadKind::Basis)
        .map(|s| (s.leg_a.as_str(), s))
        .collect();
    let rows: Vec<Vec<String>> = inp
        .curve
        .iter()
        .filter(|c| Some(c.as_of) == curve_date)
        .take(12)
        .map(|c| {
            let basis = basis_by_contract
                .iter()
                .find(|(k, _)| {
                    k.ends_with(&format!(":{}", c.tenor))
                        && k.contains(if c.gpu == GpuClass::B200 {
                            "b200"
                        } else {
                            "h100"
                        })
                        && k.starts_with("cme")
                })
                .map(|(_, s)| {
                    format!(
                        "{} (z {})",
                        f(s.value, 3),
                        s.z.map(|z| f(z, 2)).unwrap_or("-".into())
                    )
                })
                .unwrap_or("-".into());
            vec![
                c.gpu.to_string(),
                c.tenor.to_string(),
                f(c.fair_value, 4),
                f(c.srmc_floor, 3),
                f(c.lrmc_ceiling, 3),
                format!("{:.0}%", c.utilization * 100.0),
                basis,
            ]
        })
        .collect();
    md_table(
        &mut md,
        &[
            "gpu",
            "tenor",
            "fair value",
            "cash floor",
            "scarcity ceiling",
            "utilization",
            "CME basis vs nowcast",
        ],
        &rows,
    );

    // 4. Spreads
    md.push_str("## 4. Spreads\n\n");
    let rows: Vec<Vec<String>> = inp
        .spreads
        .iter()
        .filter(|s| {
            s.date == d
                && matches!(
                    s.kind,
                    SpreadKind::Calendar | SpreadKind::CrossIndex | SpreadKind::CrossGpu
                )
        })
        .map(|s| {
            vec![
                s.kind.to_string(),
                s.spread_id.clone(),
                f(s.value, 4),
                f(s.fair_value, 4),
                s.z.map(|z| f(z, 2)).unwrap_or("-".into()),
            ]
        })
        .collect();
    md_table(&mut md, &["kind", "spread", "value", "fair", "z"], &rows);

    // 5. Spark spreads
    md.push_str("## 5. Compute spark spreads by hub\n\n");
    md.push_str("Full spread = price - power - capacity - (depreciation + colo + opex). Cash spread = price - power - capacity. Breakeven utilization is the fleet utilization at which the full spread is zero.\n\n");
    let rows: Vec<Vec<String>> = inp
        .spreads
        .iter()
        .filter(|s| s.date == d && s.kind == SpreadKind::SparkSpread)
        .map(|s| {
            let i = crate::strategy::spread_inputs(s);
            vec![
                s.gpu.to_string(),
                s.leg_b.clone(),
                f(i.get("price").copied().unwrap_or(f64::NAN), 3),
                f(i.get("power_usd_mwh").copied().unwrap_or(f64::NAN), 1),
                f(i.get("power_cost").copied().unwrap_or(f64::NAN), 4),
                f(i.get("capacity_cost").copied().unwrap_or(f64::NAN), 4),
                f(s.value, 3),
                f(s.fair_value, 3),
                i.get("breakeven_utilization")
                    .map(|u| {
                        if u.is_finite() {
                            format!("{:.0}%", u * 100.0)
                        } else {
                            "n/a".into()
                        }
                    })
                    .unwrap_or("-".into()),
            ]
        })
        .collect();
    md_table(
        &mut md,
        &[
            "gpu",
            "hub",
            "price",
            "power $/MWh",
            "power $/GPU-h",
            "capacity $/GPU-h",
            "full spread",
            "cash spread",
            "breakeven util",
        ],
        &rows,
    );
    let rows: Vec<Vec<String>> = inp
        .spreads
        .iter()
        .filter(|s| s.date == d && s.kind == SpreadKind::CrossHubSpark)
        .map(|s| {
            vec![
                s.gpu.to_string(),
                format!("{} - {}", s.leg_a, s.leg_b),
                f(s.value, 4),
                s.z.map(|z| f(z, 2)).unwrap_or("-".into()),
            ]
        })
        .collect();
    if !rows.is_empty() {
        md.push_str("Cross-hub spark spreads:\n\n");
        md_table(&mut md, &["gpu", "hubs", "value", "z"], &rows);
    }

    // 6. Positions and P&L
    md.push_str("## 6. Positions and P&L\n\n");
    if let Some(last) = inp.equity.iter().rfind(|e| e.date <= d) {
        let month_start = Date::from_calendar_date(d.year(), d.month(), 1).unwrap();
        let mtd: f64 = inp
            .equity
            .iter()
            .filter(|e| e.date >= month_start && e.date <= d)
            .map(|e| e.daily_pnl.to_f64().unwrap_or(0.0))
            .sum();
        summary.push(("equity".into(), last.equity.to_string()));
        summary.push(("daily_pnl".into(), last.daily_pnl.to_string()));
        summary.push(("mtd_pnl".into(), f(mtd, 2)));
        let mut rows = vec![
            vec!["equity".into(), last.equity.round_dp(2).to_string()],
            vec!["daily P&L".into(), last.daily_pnl.round_dp(2).to_string()],
            vec!["month-to-date P&L".into(), f(mtd, 2)],
            vec![
                "gross notional".into(),
                last.gross_notional.round_dp(0).to_string(),
            ],
            vec!["open positions".into(), last.open_positions.to_string()],
        ];
        if let Some((max_gross, max_hours)) = inp.risk_limits {
            let g = last.gross_notional.to_f64().unwrap_or(0.0);
            rows.push(vec![
                "gross notional limit use".into(),
                format!("{:.0}% of {:.0}", g / max_gross * 100.0, max_gross),
            ]);
            let hours: f64 = inp
                .positions
                .iter()
                .map(|p| f64::from(p.qty) * 1000.0)
                .sum::<f64>()
                .abs();
            rows.push(vec![
                "net GPU-hour limit use".into(),
                format!("{:.0}% of {:.0}", hours / max_hours * 100.0, max_hours),
            ]);
        }
        if let Some(m) = inp.metrics {
            rows.push(vec![
                "backtest return".into(),
                format!("{:.2}%", m.total_return * 100.0),
            ]);
            rows.push(vec!["backtest Sharpe (daily, 252)".into(), f(m.sharpe, 2)]);
            rows.push(vec![
                "backtest max drawdown".into(),
                format!("{:.2}%", m.max_drawdown * 100.0),
            ]);
            rows.push(vec![
                "hit rate".into(),
                format!("{:.0}%", m.hit_rate * 100.0),
            ]);
            rows.push(vec!["fees paid".into(), f(m.fees_paid, 2)]);
            rows.push(vec![
                "risk events / stops".into(),
                format!("{} / {}", m.risk_events, m.stop_events),
            ]);
            summary.push(("backtest_return".into(), f(m.total_return, 6)));
            summary.push(("sharpe".into(), f(m.sharpe, 4)));
            summary.push(("max_drawdown".into(), f(m.max_drawdown, 6)));
        }
        md_table(&mut md, &["metric", "value"], &rows);
        let rows: Vec<Vec<String>> = inp
            .positions
            .iter()
            .map(|p| {
                vec![
                    p.strategy.clone(),
                    p.contract_id.to_string(),
                    p.qty.to_string(),
                    p.avg_price.to_string(),
                    p.mark.to_string(),
                    p.unrealized_pnl.round_dp(2).to_string(),
                ]
            })
            .collect();
        md.push_str("Open positions:\n\n");
        md_table(
            &mut md,
            &[
                "strategy",
                "contract",
                "qty",
                "avg price",
                "mark",
                "unrealized",
            ],
            &rows,
        );
    } else {
        md.push_str("_no paper book yet: run `basis backtest`_\n\n");
    }

    // 7. Signals
    md.push_str("## 7. Signals today\n\n");
    let rows: Vec<Vec<String>> = inp
        .signals
        .iter()
        .filter(|s| s.date == d)
        .map(|s| {
            vec![
                s.strategy.clone(),
                s.contract_id.to_string(),
                s.side.to_string(),
                s.qty.to_string(),
                s.intent.to_string(),
                f(s.z, 2),
                s.reason.clone(),
            ]
        })
        .collect();
    md_table(
        &mut md,
        &[
            "strategy", "contract", "side", "qty", "intent", "z", "reason",
        ],
        &rows,
    );

    // 8. Data quality
    md.push_str("## 8. Data quality\n\n");
    let mut dq: Vec<Vec<String>> = Vec::new();
    let today_obs: Vec<&PriceObservation> =
        inp.observations.iter().filter(|o| o.date() == d).collect();
    let mut by_source: BTreeMap<(String, ProviderTier), usize> = BTreeMap::new();
    for o in &today_obs {
        *by_source.entry((o.source.clone(), o.tier)).or_insert(0) += 1;
    }
    for ((src, tier), n) in &by_source {
        dq.push(vec![
            "observations".into(),
            format!("{src}/{tier}"),
            n.to_string(),
        ]);
    }
    let today_std: Vec<&StandardizedObservation> =
        inp.standardized.iter().filter(|s| s.date == d).collect();
    let outliers = today_std
        .iter()
        .filter(|s| s.flags.contains("outlier"))
        .count();
    let capped = today_std
        .iter()
        .filter(|s| s.flags.contains("capped"))
        .count();
    let new_p = today_std
        .iter()
        .filter(|s| s.flags.contains("new_provider"))
        .count();
    dq.push(vec![
        "standardized rows".into(),
        "all indices".into(),
        today_std.len().to_string(),
    ]);
    dq.push(vec![
        "outliers removed".into(),
        "all indices".into(),
        outliers.to_string(),
    ]);
    dq.push(vec![
        "weights capped".into(),
        "all indices".into(),
        capped.to_string(),
    ]);
    dq.push(vec![
        "new providers".into(),
        "all indices".into(),
        new_p.to_string(),
    ]);
    // provider concentration: top provider share of weight per index
    let mut by_index: BTreeMap<String, BTreeMap<String, f64>> = BTreeMap::new();
    for s in &today_std {
        *by_index
            .entry(s.index_id.to_string())
            .or_default()
            .entry(s.provider.clone())
            .or_insert(0.0) += s.weight;
    }
    for (idx, prov) in &by_index {
        let total: f64 = prov.values().sum();
        if let Some((p, w)) = prov.iter().max_by(|a, b| a.1.partial_cmp(b.1).unwrap()) {
            dq.push(vec![
                "top provider weight".into(),
                idx.clone(),
                format!("{p} {:.0}%", w / total * 100.0),
            ]);
        }
    }
    // stale sources: sources seen in the last 30 days but not today
    let recent: BTreeSet<&str> = inp
        .observations
        .iter()
        .filter(|o| o.date() <= d && (d - o.date()).whole_days() <= 30)
        .map(|o| o.source.as_str())
        .collect();
    let today_src: BTreeSet<&str> = today_obs.iter().map(|o| o.source.as_str()).collect();
    for s in recent.difference(&today_src) {
        dq.push(vec![
            "stale source".into(),
            s.to_string(),
            "no observations today".into(),
        ]);
    }
    md_table(&mut md, &["check", "scope", "value"], &dq);
    summary.push(("observations_today".into(), today_obs.len().to_string()));
    summary.push(("outliers_today".into(), outliers.to_string()));

    Report {
        markdown: md,
        summary,
        data_quality: dq,
    }
}
